# Generated by Django 5.2.9 on 2026-01-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_grade_level_and_more'),
        ('core', '0004_diagnosticquestion_studentprofile_diagnosticanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
