# Generated by Django 5.2.9 on 2026-01-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_grade_level_and_more'),
        ('core', '0006_remove_question_test_remove_studentanswer_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
